# Generated by Django 4.2.1 on 2023-06-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('salary_scale', models.CharField(max_length=4)),
                ('department', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('commitment', models.CharField(max_length=20)),
            ],
        ),
    ]
